project6/config/routes.rb
Rails.application.routes.draw do

  resources :presentations do
  	resources :feedbacks
  end
  
  root "presentations#index"
  devise_for :users, controllers: { registrations: 'registrations' }

  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

project6/app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new # guest user (not logged in)
      if user.has_role? :admin
        can :manage, :all
      else
        can :read, :all
      end
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

project6/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

project6/app/models/feedback.rb
class Feedback < ApplicationRecord
	belongs_to :presentation
	belongs_to :user

end

project6/app/models/presentation.rb
class Presentation < ApplicationRecord
    belongs_to :user
	has_many :feedbacks, dependent: :destroy

	resourcify
end

project6/app/models/role.rb
class Role < ApplicationRecord
  has_and_belongs_to_many :users, :join_table => :users_roles
  
  belongs_to :resource,
             :polymorphic => true,
             :optional => true
  

  validates :resource_type,
            :inclusion => { :in => Rolify.resource_types },
            :allow_nil => true

  scopify
end

project6/app/models/user.rb
class User < ApplicationRecord
  rolify
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :presentations, dependent: :destroy
end

project6/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

project6/app/controllers/feedbacks_controller.rb
class FeedbacksController < ApplicationController
  before_action :authenticate_user!
  before_action :set_feedback, only: %i[ show edit update destroy ]
  before_action :set_presentation, only: [:create, :edit, :show, :update, :destroy]


  def create
    @feedback = @presentation.feedbacks.create(params[:feedback].permit(:feedback, :presentation_id))
    @feedback.user_id = current_user.id

    respond_to do |format|
      if @feedback.save
        format.html { redirect_to presentation_path(@presentation) }
        format.js # renders create.js.erb
      else
        format.html { redirect_to presentation_path(@presentation), notice: "Feedback did not save. Please try again."}
        format.js
      end
    end
  end

  def new
  end


  def destroy
    @feedback = @presentation.feedbacks.find(params[:id])
    @feedback.destroy
    redirect_to presentation_path(@presentation)
  end

  def edit
    @presentation = Presentation.find(params[:presentation_id])
    @feedback = @presentation.feedbacks.find(params[:id])
  end

  def update
    @feedback = @presentation.feedbacks.find(params[:id])
     respond_to do |format|
      if @feedback.update(feedback_params)
        format.html { redirect_to presentation_path(@presentation), notice: 'Feedback was successfully updated.' }
      else
        format.html { render :edit }
        format.json { render json: @feedback.errors, status: :unprocessable_entity }
      end
    end
  end

  def show
  end

  private

  def set_presentation
    @presentation = Presentation.find(params[:presentation_id])
  end

  def set_feedback
    @feedback = Feedback.find(params[:id])
  end

  def feedback_params
    params.require(:feedback).permit(:feedback)
  end
end

project6/app/controllers/presentations_controller.rb
class PresentationsController < ApplicationController
  before_action :set_presentation, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, except: [:index, :show]
  # GET /presentations or /presentations.json
  def index
    @presentations = Presentation.all.order('created_at desc')
    @users = User.all.order('created_at desc')
  end

  # GET /presentations/1 or /presentations/1.json
  def show
    @presentations = Presentation.all.order('created_at desc')
    @feedbacks = Feedback.all
  end

  # GET /presentations/new
  def new
    @presentation = current_user.presentations.build
  end

  # GET /presentations/1/edit
  def edit
  end

  # POST /presentations or /presentations.json
  def create
    @presentation = current_user.presentations.build(presentation_params)

    respond_to do |format|
      if @presentation.save
        format.html { redirect_to @presentation, notice: "Presentation was successfully created." }
        format.json { render :show, status: :created, location: @presentation }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @presentation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /presentations/1 or /presentations/1.json
  def update
    respond_to do |format|
      if @presentation.update(presentation_params)
        format.html { redirect_to @presentation, notice: "Presentation was successfully updated." }
        format.json { render :show, status: :ok, location: @presentation }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @presentation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /presentations/1 or /presentations/1.json
  def destroy
    @presentation.destroy
    respond_to do |format|
      format.html { redirect_to presentations_url, notice: "Presentation was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_presentation
      @presentation = Presentation.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def presentation_params
      params.require(:presentation).permit(:title, :author, :grade)
    end
end

project6/app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  private

  def sign_up_params
    params.require(:user).permit(:username, :email, :password, :password_confirmation)
  end

  def account_update_params
    params.require(:user).permit(:username, :email, :password, :password_confirmation, :current_password)
  end

end

project6/app/helpers/application_helper.rb
module ApplicationHelper
  def has_role?(role)
    current_user && current_user.has_role?(role)
  end
end

project6/app/views/feedbacks/_feedback.html.erb
<div>
  <article>
    <div>
      
    </div>
    <div>
      <div>
        <p>
          <strong><%= feedback.user.username %></strong> 
          <br/>
          <%= feedback.feedback %>
        </p>
      </div>

      <nav>
        <div>

          </a>
          <a>
            <% if has_role?(:admin) %>
            <%= link_to [feedback.presentation, feedback],
                method: :delete, data: {confirm: "Are you sure?" } do %>
            <span><i>Delete</i></span>
            <% end %>
            <% end %>

          </a>
        </div>
      </nav>
</br>
    </div>
  </article>
</div>

project6/app/views/feedbacks/_form.html.erb
<%= simple_form_for([@presentation, @presentation.feedbacks.build], remote: true) do |f| %>

</br>
<div>
  <div class="form-group"> 
    <%= f.input :feedback, label: false %>
  </div>
</div>
</br>
<%= f.button :submit, 'Submit', class:"btn btn-primary" %>

<% end %>

project6/app/views/layouts/_alerts.html.erb
<div class="alert alert-success alert-dismissible fade show" role="alert">
  <%= notice %>
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>

project6/app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">

    <title>Project6</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'presentations/header' %> 
    <div class="container">

      <% if notice %>
        <%= render 'layouts/alerts'%>
      <% end %>
      
      <% if flash[:alert] %>
        <div>
          <p><%= alert %></p>
        </div>
      <% end %>

      
    </div>

<%# No use but deleting cause trouble %>
      <div>
        <div>
          <% if user_signed_in? %>
          <div>
            <% if has_role?(:admin) %>
            <% end %>
          </div>
         <% else %>
          <% end %>
        </div>
    </div>
<%# No use but deleting cause trouble %>

<section>
  <div>
    <%= yield %>
  </div>
</section>


    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.bundle.min.js" integrity="sha384-JEW9xMcG8R+pH31jmWH6WWP0WintQrMb4s7ZOdauHnUtxwoG2vI5DkLtS3qm9Ekf" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.1/dist/umd/popper.min.js" integrity="sha384-SR1sx49pcuLnqZUnnPwx6FCym0wLsk5JZuNx2bPPENzswTNFaQU1RDvt3wT4gWFG" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.min.js" integrity="sha384-j0CNLUeiqtyaRmlzUHCPZ+Gy5fQu0dQ6eZ/xAww941Ai1SxSY+0EQqNXNE6DZiVc" crossorigin="anonymous"></script>
    -->
  </body>
</html>

project6/app/views/presentations/_form.html.erb
<%= simple_form_for(@presentation) do |f| %>
  <%= f.error_notification %>

  </br>
  <div>
    <div>
      <%= f.input :title, required: true%>
    </div>
  </div>

  </br>
  <div>
    <div>
      <%= f.input :author, required: true%>
    </div>
  </div>

  </br>
  <div>
    <div>
      <%= f.input :grade, required: false%>
    </div>
  </div>

  
  </br>
  <div>
    <div>
      <%= f.button :submit, class:"btn btn-primary" %>
    </div>
    </br>
  </div>

<% end %>

project6/app/views/presentations/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">

  <div class="container-fluid">
  	<%= link_to 'TeamOne', root_path, class:"navbar-brand" %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        
        <% if user_signed_in? %>
          <li class="nav-item">
            <%= link_to 'Sign Out', destroy_user_session_path, method: :delete, class:"nav-link" %>
          </li>

          <li class="nav-item">
            <%= link_to 'Edit Profile', edit_user_registration_path, class:"nav-link" %>
          </li>

        <% else %>
          <li class="nav-item">
            <%= link_to 'Sign In', new_user_session_path, class:"nav-link" %>
          </li>

          <li class="nav-item">
            <%= link_to 'Sign Up', new_user_registration_path, class:"nav-link" %>
          </li>
        <% end %>
        

      </ul>
    </div>
  </div>
</nav>

project6/app/views/presentations/edit.html.erb
<div class="container">
</br>
<h1>Editing Presentation</h1>

<%= render 'form', presentation: @presentation %>

<%= link_to 'Show', @presentation %> |
<%= link_to 'Back', presentations_path %>

project6/app/views/presentations/index.html.erb
<div class="container">

</br>
<div>
  <h1> Welcome to TeamOne's presentation feedback website! </h1>  
</div>

<% if has_role?(:admin) %>
</br>
  <h3>Presentations</h3>
  <table class="table table-striped">
    <thead>
      <tr>
        <th>Title</th>
        <th>Author</th>
        <th>Grade</th>
        <th colspan="3"></th>
      </tr>
    </thead>

  <tbody>
    <% @presentations.each do |presentation| %>
      <tr>
        <td><%= presentation.title %></td>
        <td><%= presentation.author %></td>
        <td><%= presentation.grade %></td>
        <td><%= link_to 'Show', presentation %></td>
        <td><%= link_to 'Edit', edit_presentation_path(presentation) %></td>
        <td><%= link_to 'Destroy', presentation, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

  </br>
  <h3>Students</h3>
  <table class="table table-striped">
    <thead>
      <tr>
        <th>Student Name</th>
        <th>Email</th>
        <th colspan="3"></th>
      </tr>
    </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <% if not user.has_role?(:admin) %>
        <td><%= user.username %></td>
        <td><%= user.email %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

</br>



<%= link_to 'New Presentation', new_presentation_path, class:"btn btn-primary" %>

<% end %>

<div>
  </br>
  </br>
  <h3>Latest Presentations</h3>
  <div>
    <% @presentations.each do |presentation| %>
      <div>
        <div class="jumbotron">
        </br>
        <p class="lead"><%= presentation.author %></p>
        <div>
        <%= link_to presentation do %>
          <%= truncate(presentation.title, length: 140) %>
        <% end %>
        
        <p><em><small>Posted by <%= presentation.user.username %></small></em></p>
        <hr class="my-4">
  </div>
    
      </div>
      </div>
    <% end %>
  </div>
</div>

project6/app/views/presentations/new.html.erb
<div class="container">

</br>
<h1 class="title is-size-4">New Presentation</h1>

<%= render 'form', presentation: @presentation %>

<%= link_to 'Back', presentations_path, class:"btn btn-primary" %>

project6/app/views/presentations/show.html.erb
<div class="container">

</br>
<% if has_role?(:admin) %>
  <div class="jumbotron">
  <h1 class="display-4"> Event: <%= @presentation.title %></h1>
  </br>
  <p class="lead">
    <strong>Title:</strong>
    <%= @presentation.title %>
  </p>

  <p class="lead">
    <strong>Author:</strong>
    <%= @presentation.author %>
  </p>

  <p class="lead">
    <strong>Grade:</strong>
    <%= @presentation.grade %>
  </p>
  
  </div>

  <%= link_to 'Edit', edit_presentation_path(@presentation), class:"btn btn-primary" %>
  <%= link_to 'Back', presentations_path, class:"btn btn-primary" %>
  </br>
<% end %>

<div>
  <div>
    

    <div>
      <div>

        
      </div>
    </div>
    </br>
    <hr/>
    <p>There are <%= @presentation.feedbacks.count %> feedbacks now.</p>

    <div id="presentation-feedbacks">
    	<%= render @presentation.feedbacks %>
    </div>



    <hr/>
    </br>
    <h3>Leave a feedback</h3>
    <% if user_signed_in? %>
    	<%= render 'feedbacks/form' %>
    <% else %>
      <p>To leave a feedback you need to <%= link_to 'login', new_user_session_path %>. Don't have an account?
      <%= link_to 'Sign up', new_user_registration_path %> for one.</p>
    <% end %>

  </div>


</div>